version: '3.8'

services:
  zart:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: zart-api
      POSTGRES_PASSWORD: T{MF1x&a-rFL
      POSTGRES_DB: zart-postgresdb
      JWT_SECRET: rX7pL9qK3mF1bN4sT6wY8zC2vA5hJ0eD
      GOOGLE_CLIENT_ID: 299469207929-bbhunpft9bfr9gk207m0s0i99a4docm7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: http://localhost:3010/v1/auth/google/redirect

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: zart-api
      POSTGRES_DB: zart-postgresdb
      POSTGRES_PASSWORD: T{MF1x&a-rFL
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: