version: '3.9'

services:
  zart:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zart-api
      POSTGRES_DB: zart-postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: